# Setup
title:               Raj
tagline:             'Notebook'
description:         ''
url:                 https://raj.se
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Raj
  email:             info@raj.se

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

# Collections
collections:
  - books
